### ISSUE TITLE
Qferrer\Mjml\Twig\MjmlExtension::__construct() argument issue

### ISSUE THREAD

**Issue by fd6130** [qferr/mjml-twig#8]
I just upgrade my project from Symfony 5.4 to Symfony 6 and i encounter this issue.

```
Qferrer\Mjml\Twig\MjmlExtension::__construct():

Argument #1 ($renderer) must be of type Qferrer\Mjml\Renderer\RendererInterface, 

Qferrer\Mjml\Renderer\BinaryRenderer given
```

My services.yaml:

```yaml
mjml_renderer:
        class: Qferrer\Mjml\Renderer\BinaryRenderer
        arguments:
            - '%kernel.project_dir%/node_modules/.bin/mjml'

    Qferrer\Mjml\Twig\MjmlExtension:
        arguments: ['@mjml_renderer']
        tags: ['twig.extension']
```

UPDATE:
~~But fresh new Symfony 6 project have no issue at all, not sure what is the culprit causing argument type error. Any clue?~~

It is because the current code using `Qferrer\Mjml\Renderer\RendererInterface` but the real namespace is `Qferrer\Mjml\RendererInterface`. PR will be create shortly.
